-- FOOD_PRODUCT와 FOOD_ORDER 테이블에서 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회하는 SQL문을 작성해주세요.
-- 이때 결과는 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 식품 ID를 기준으로 오름차순 정렬해주세요.

SELECT fp.PRODUCT_ID AS PRODUCT_ID, fp.PRODUCT_NAME AS PRODUCT_NAME, SUM(fo.AMOUNT * fp.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT fp
JOIN FOOD_ORDER fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE fo.PRODUCE_DATE >= DATE '2022-05-01' AND fo.PRODUCE_DATE < DATE '2022-06-01'
GROUP BY fp.PRODUCT_ID, fp.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID;